apiVersion: v1
kind: Service
metadata:
  name: gym-telemetry-service
spec:
  type: NodePort
  selector:
    app: gym-telemetry
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001